"""fix_telegram_id_bigint

Revision ID: 540a08dbe64b
Revises: a274247da3b4
Create Date: 2025-11-20 22:19:51.647172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540a08dbe64b'
down_revision = 'a274247da3b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###

